# Generated by Django 4.2.13 on 2024-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataproduct",
            name="processed_cell_type_counts",
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataproduct",
            name="raw_cell_type_counts",
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
