# Generated by Django 4.2.14 on 2024-07-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_products", "0002_dataproduct_processed_cell_type_counts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissue",
            name="tissuecode",
            field=models.CharField(default="", max_length=2),
            preserve_default=False,
        ),
    ]
