# Generated by Django 4.2.13 on 2024-08-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_products", "0003_tissue_tissuecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataproduct",
            name="processed_file_sizes_bytes",
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataproduct",
            name="raw_file_size_bytes",
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dataproduct",
            name="processed_total_cell_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataproduct",
            name="raw_total_cell_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
