# Generated by Django 4.2.11 on 2024-08-29 22:07

import data_products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data_products", "0004_dataproduct_processed_file_sizes_bytes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataproduct",
            name="assay",
            field=models.ForeignKey(
                default=data_products.models.Assay.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_products.assay",
            ),
        ),
    ]
