# Generated by Django 4.2.11 on 2024-09-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_products", "0009_remove_dataset_data_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataproduct",
            name="processed_file_sizes_bytes",
            field=models.PositiveBigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dataproduct",
            name="raw_file_size_bytes",
            field=models.PositiveBigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
